# MySQL - local installation
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: root
    password: pass123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-server: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value_serializer: org.apache.kafka.common.serialization.StringSerializer

  redis:
    host: localhost
    port: 6379
